export default [
  {
    "url": "https://api.github.com/repos/xgqfrms/vue/issues/85",
    "repository_url": "https://api.github.com/repos/xgqfrms/vue",
    "labels_url": "https://api.github.com/repos/xgqfrms/vue/issues/85/labels{/name}",
    "comments_url": "https://api.github.com/repos/xgqfrms/vue/issues/85/comments",
    "events_url": "https://api.github.com/repos/xgqfrms/vue/issues/85/events",
    "html_url": "https://github.com/xgqfrms/vue/issues/85",
    "id": 551248680,
    "node_id": "MDU6SXNzdWU1NTEyNDg2ODA=",
    "number": 85,
    "title": "angular & controller & $inject & vue ",
    "user": {
      "login": "xgqfrms",
      "id": 7291672,
      "node_id": "MDQ6VXNlcjcyOTE2NzI=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/7291672?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/xgqfrms",
      "html_url": "https://github.com/xgqfrms",
      "followers_url": "https://api.github.com/users/xgqfrms/followers",
      "following_url": "https://api.github.com/users/xgqfrms/following{/other_user}",
      "gists_url": "https://api.github.com/users/xgqfrms/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/xgqfrms/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/xgqfrms/subscriptions",
      "organizations_url": "https://api.github.com/users/xgqfrms/orgs",
      "repos_url": "https://api.github.com/users/xgqfrms/repos",
      "events_url": "https://api.github.com/users/xgqfrms/events{/privacy}",
      "received_events_url": "https://api.github.com/users/xgqfrms/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 1792862611,
        "node_id": "MDU6TGFiZWwxNzkyODYyNjEx",
        "url": "https://api.github.com/repos/xgqfrms/vue/labels/angular%20&%20controller%20&%20$inject%20&%20vue",
        "name": "angular & controller & $inject & vue",
        "color": "b60205",
        "default": false,
        "description": "angular & controller & $inject & vue"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-01-17T07:23:20Z",
    "updated_at": "2020-01-17T07:23:56Z",
    "closed_at": null,
    "author_association": "OWNER",
    "body": "# angular & controller & $inject & vue \r\n\r\nhttps://github.com/xgqfrms/angular-1.4.3/issues/6",
    "score": 54.8873
  },
  {
    "url": "https://api.github.com/repos/froala/angular-froala-wysiwyg/issues/362",
    "repository_url": "https://api.github.com/repos/froala/angular-froala-wysiwyg",
    "labels_url": "https://api.github.com/repos/froala/angular-froala-wysiwyg/issues/362/labels{/name}",
    "comments_url": "https://api.github.com/repos/froala/angular-froala-wysiwyg/issues/362/comments",
    "events_url": "https://api.github.com/repos/froala/angular-froala-wysiwyg/issues/362/events",
    "html_url": "https://github.com/froala/angular-froala-wysiwyg/issues/362",
    "id": 539037563,
    "node_id": "MDU6SXNzdWU1MzkwMzc1NjM=",
    "number": 362,
    "title": "Support for Angular 9",
    "user": {
      "login": "MartinWa",
      "id": 497015,
      "node_id": "MDQ6VXNlcjQ5NzAxNQ==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/497015?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MartinWa",
      "html_url": "https://github.com/MartinWa",
      "followers_url": "https://api.github.com/users/MartinWa/followers",
      "following_url": "https://api.github.com/users/MartinWa/following{/other_user}",
      "gists_url": "https://api.github.com/users/MartinWa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MartinWa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MartinWa/subscriptions",
      "organizations_url": "https://api.github.com/users/MartinWa/orgs",
      "repos_url": "https://api.github.com/users/MartinWa/repos",
      "events_url": "https://api.github.com/users/MartinWa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MartinWa/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 5,
    "created_at": "2019-12-17T12:31:30Z",
    "updated_at": "2020-01-15T17:54:19Z",
    "closed_at": null,
    "author_association": "NONE",
    "body": "Renderer is deprecated in Angular 9 so we can not update because you are still dependent on them. A fix was merged in from this [PR](https://github.com/froala/angular-froala-wysiwyg/pull/349) but it has not been released. Could you please do a release so that we can update",
    "score": 54.79349
  },
  {
    "url": "https://api.github.com/repos/nowakprojects/DrogaNowoczesnegoArchitekta/issues/117",
    "repository_url": "https://api.github.com/repos/nowakprojects/DrogaNowoczesnegoArchitekta",
    "labels_url": "https://api.github.com/repos/nowakprojects/DrogaNowoczesnegoArchitekta/issues/117/labels{/name}",
    "comments_url": "https://api.github.com/repos/nowakprojects/DrogaNowoczesnegoArchitekta/issues/117/comments",
    "events_url": "https://api.github.com/repos/nowakprojects/DrogaNowoczesnegoArchitekta/issues/117/events",
    "html_url": "https://github.com/nowakprojects/DrogaNowoczesnegoArchitekta/issues/117",
    "id": 544195429,
    "node_id": "MDU6SXNzdWU1NDQxOTU0Mjk=",
    "number": 117,
    "title": "DDD in Angular | Sustainable Angular Architectures",
    "user": {
      "login": "nowakprojects",
      "id": 18637116,
      "node_id": "MDQ6VXNlcjE4NjM3MTE2",
      "avatar_url": "https://avatars0.githubusercontent.com/u/18637116?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nowakprojects",
      "html_url": "https://github.com/nowakprojects",
      "followers_url": "https://api.github.com/users/nowakprojects/followers",
      "following_url": "https://api.github.com/users/nowakprojects/following{/other_user}",
      "gists_url": "https://api.github.com/users/nowakprojects/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nowakprojects/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nowakprojects/subscriptions",
      "organizations_url": "https://api.github.com/users/nowakprojects/orgs",
      "repos_url": "https://api.github.com/users/nowakprojects/repos",
      "events_url": "https://api.github.com/users/nowakprojects/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nowakprojects/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 1597195591,
        "node_id": "MDU6TGFiZWwxNTk3MTk1NTkx",
        "url": "https://api.github.com/repos/nowakprojects/DrogaNowoczesnegoArchitekta/labels/topic:%20domain_driven_design",
        "name": "topic: domain_driven_design",
        "color": "f7b899",
        "default": false,
        "description": ""
      },
      {
        "id": 1597002364,
        "node_id": "MDU6TGFiZWwxNTk3MDAyMzY0",
        "url": "https://api.github.com/repos/nowakprojects/DrogaNowoczesnegoArchitekta/labels/type:%20dodatkowe_materialy",
        "name": "type: dodatkowe_materialy",
        "color": "510d99",
        "default": false,
        "description": ""
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": {
      "login": "nowakprojects",
      "id": 18637116,
      "node_id": "MDQ6VXNlcjE4NjM3MTE2",
      "avatar_url": "https://avatars0.githubusercontent.com/u/18637116?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nowakprojects",
      "html_url": "https://github.com/nowakprojects",
      "followers_url": "https://api.github.com/users/nowakprojects/followers",
      "following_url": "https://api.github.com/users/nowakprojects/following{/other_user}",
      "gists_url": "https://api.github.com/users/nowakprojects/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nowakprojects/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nowakprojects/subscriptions",
      "organizations_url": "https://api.github.com/users/nowakprojects/orgs",
      "repos_url": "https://api.github.com/users/nowakprojects/repos",
      "events_url": "https://api.github.com/users/nowakprojects/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nowakprojects/received_events",
      "type": "User",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "nowakprojects",
        "id": 18637116,
        "node_id": "MDQ6VXNlcjE4NjM3MTE2",
        "avatar_url": "https://avatars0.githubusercontent.com/u/18637116?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/nowakprojects",
        "html_url": "https://github.com/nowakprojects",
        "followers_url": "https://api.github.com/users/nowakprojects/followers",
        "following_url": "https://api.github.com/users/nowakprojects/following{/other_user}",
        "gists_url": "https://api.github.com/users/nowakprojects/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/nowakprojects/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/nowakprojects/subscriptions",
        "organizations_url": "https://api.github.com/users/nowakprojects/orgs",
        "repos_url": "https://api.github.com/users/nowakprojects/repos",
        "events_url": "https://api.github.com/users/nowakprojects/events{/privacy}",
        "received_events_url": "https://api.github.com/users/nowakprojects/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2019-12-31T13:58:43Z",
    "updated_at": "2019-12-31T13:58:43Z",
    "closed_at": null,
    "author_association": "OWNER",
    "body": "https://www.softwarearchitekt.at/aktuelles/sustainable-angular-architectures-1/",
    "score": 54.637806
  },
  {
    "url": "https://api.github.com/repos/Team-Atrium/angular-starter/issues/2",
    "repository_url": "https://api.github.com/repos/Team-Atrium/angular-starter",
    "labels_url": "https://api.github.com/repos/Team-Atrium/angular-starter/issues/2/labels{/name}",
    "comments_url": "https://api.github.com/repos/Team-Atrium/angular-starter/issues/2/comments",
    "events_url": "https://api.github.com/repos/Team-Atrium/angular-starter/issues/2/events",
    "html_url": "https://github.com/Team-Atrium/angular-starter/issues/2",
    "id": 549165997,
    "node_id": "MDU6SXNzdWU1NDkxNjU5OTc=",
    "number": 2,
    "title": "New Angular UI project",
    "user": {
      "login": "kvkirthy",
      "id": 2632323,
      "node_id": "MDQ6VXNlcjI2MzIzMjM=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/2632323?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kvkirthy",
      "html_url": "https://github.com/kvkirthy",
      "followers_url": "https://api.github.com/users/kvkirthy/followers",
      "following_url": "https://api.github.com/users/kvkirthy/following{/other_user}",
      "gists_url": "https://api.github.com/users/kvkirthy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kvkirthy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kvkirthy/subscriptions",
      "organizations_url": "https://api.github.com/users/kvkirthy/orgs",
      "repos_url": "https://api.github.com/users/kvkirthy/repos",
      "events_url": "https://api.github.com/users/kvkirthy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kvkirthy/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-01-13T20:34:24Z",
    "updated_at": "2020-01-13T20:34:24Z",
    "closed_at": null,
    "author_association": "NONE",
    "body": "",
    "score": 54.597416
  }
]
